# These are supported funding model platforms

github: [likhonsexikh]
# patreon: # your_patreon_username
# open_collective: # your_opencollective_username
# ko_fi: # your_kofi_username
# tidelift: # your_tidelift_platform/package-name
# community_bridge: # your_communitybridge_project
# liberapay: # your_liberapay_username
# issuehunt: # your_issuehunt_username
# otechie: # your_otechie_username
# lfx_crowdfunding: # your_lfx_crowdfunding_project
custom: # Add custom sponsorship URLs
